### PR TITLE
Reduced FCL_Elliptic_ZZ.ecdsa_verify gas cost ( -2600 gas )

### PR DESCRIPTION
**Pull request by jayden-sudo**
### With the code equivalent, executing `FCL_Elliptic_ZZ.ecdsa_verify` reduced gas cost by <u> 2600 gas</u>:

|        | Gas        |
| ------ | ---------- |
| Before | 212970 gas |
| After  | 210370 gas |

- Testing step:
    1. ```shell 
       cd solidity/tests/WebAuthn_forge
       forge test --ffi --match-test test_webauthn_Base64URL_checkSignature --gas-report 
       ```

### Gas Optimization Records for ecdsa_verify:

1. Changed from calling ModExp to staticcall ModExp, reducing the number of parameters.

   1. The function was also changed to `view`.

2. Replaced `uint256[6] memory pointer` with `pointer := mload(0x40)`, reducing calls like `MSTORE(0x40)`.

3. Performed assembly optimizations.
   1. ```solidity 
       // before 
       if eq(x,1){} if eq(x,2)
       // after
       switch x case 1{} case 2{} ```

   3. ```solidity
        // before
        eq(x, 0)
        // after
        iszero(x) ```

5. Calldata cache, avoid frequent call of calldataload

   1. ```solidity 
       function f(uint256[2] calldata rs) returns (bool success){ 
       // before 
       if (rs[0] == 0 || rs[0] >= n || rs[1] == 0 || rs[1] >= n){ return false; } 
       // after 
       uint256 r = rs[0]; 
       uint256 s = rs[1]; 
      
       } ```

### CODE REVIEW

**Comment by rdubois-crypto** [comment]
This is ok for me, just a question for the switch case intead of nested if, did u test a positive impact of the gas cost ? I remember avoiding them due to lesser efficiency?

**Comment by jayden-sudo** [comment]
> This is ok for me, just a question for the switch case intead of nested if, did u test a positive impact of the gas cost ? I remember avoiding them due to lesser efficiency?

Using `switch` may lead to higher gas consumption, but it's not entirely accurate. For example, consider the following program:

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.21;

contract Test {
    function testSwitch(uint256 i) public view returns (uint256 res){
        uint256 gas = gasleft();
        assembly{
            switch i
            case 1 {
                    i := add(i,2)
            }
            case 2 {
                    i := add(i,3)
            }
            case 3 {
                    i := add(i,4)
            }
        }
        return gas - gasleft();
    }

    function testIF(uint256 i) public view returns (uint256 res){
        uint256 gas = gasleft();
        assembly{
            if eq(i,i){
                i := add(i,2)
            }
            if eq(i,2){
                i := add(i,3)
            }
            if eq(i,3){
                i := add(i,4)
            }
        }
        return gas - gasleft();
    }
}
```

When `viaIR` is `false` and `optimizer` is `false`:

- Input `i = 1`, `testSwitch = 61` gas, `testIf = 104` gas
- Input `i = 2`, `testSwitch = 83` gas, `testIf = 90` gas
- Input `i = 3`, `testSwitch = 94` gas, `testIf = 90` gas

When `viaIR` is `true` and `optimizer` is `false`:

- Input `i = 1`, `testSwitch = 53` gas, `testIf = 112` gas
- Input `i = 2`, `testSwitch = 75` gas, `testIf = 94` gas
- Input `i = 3`, `testSwitch = 92` gas, `testIf = 94` gas

Especially when `viaIR` is `true`, using `switch` often results in higher gas efficiency. In fact, the gas efficiency improvement in this PR mainly relies on [this change](https://github.com/rdubois-crypto/FreshCryptoLib/pull/18/files#diff-2490330b335cfe50463152c366decf21825153af366bb18dec4d000505cff7a4R370-R382).

But this is indeed confusing. If the first `if` condition can be satisfied, then using `switch` is clearly superior. If there are many branches in the `switch`, and often the `if` conditions are only satisfied later, using `if` might be better (of course, in such cases, we can optimize by reorder the conditions to prioritize the most frequently hit one at the top of the `switch`).

**Comment by rdubois-crypto** [comment]
Please provide two distincts PR, with and without the switch case. view one is ok, switch will depend on the concrete bench (not toy example).

**Comment by jayden-sudo** [comment]
> Please provide two distincts PR, with and without the switch case. view one is ok, switch will depend on the concrete bench (not toy example).

Okay, I'll submit it soon 🫡

**Comment by jayden-sudo** [comment]
> Please provide two distincts PR, with and without the switch case. view one is ok, switch will depend on the concrete bench (not toy example).
without 'switch': #22 , only 0.3kgas saved. (hope this PR helps you complete the gas efficiency comparison)

**Comment by rdubois-crypto** [comment]
Closed with adoption of same contributor no switch PR version. (switch case only PR can be submitted now).

**Comment by jayden-sudo** [comment]
> Closed with adoption of same contributor no switch PR version. (switch case only PR can be submitted now).

Thank you. Honestly, changing "if" to "switch" and saving 2K gas perplexed me as well. Before submitting the PR( if -> switch), I'll examine the compiled OP code, identify the reasons for saving 2K gas, ensure that this gas efficiency improvement is sustainable, and provide detailed explanations for the gas efficiency improvements in the PR.

**Pull request closed without merging**
